name: CI
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review
  push:
    branches:
      - main

env:
  NODE_VERSION: "21.x"

jobs:
  lint:
    name: Verify package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Lint
        run: pnpm ci:lint
      - name: Typecheck
        run: pnpm ci:types

  tests:
    name: Test package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: wyvox/action-setup-pnpm@v3
        with:
          node-version: "${{ env.NODE_VERSION }}"

      - name: Tests
        run: pnpm ci:specs
